# Generated by Django 2.1.2 on 2018-11-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20181117_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.FileField(upload_to='desktop/'),
        ),
    ]
